### ISSUE TITLE
E404 - Package Not Found in npm Registry

### ISSUE THREAD

**Issue by cimplify-ai** [trendy-design/llmchat#48]
Description:
I encountered a 404 Not Found error when trying to install the package @hugeicons/react via npm. It seems that the package is not available in the npm registry.

Steps to Reproduce:
Run the following command:
bash
`npm install @hugeicons/react@^0.6.1` or `npm Install`

The following error is returned:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@hugeicons%2freact - Not found
npm ERR! 404 
npm ERR! 404  '@hugeicons/react@^0.6.1' is not in this registry.
```

Expected Behavior:
The package **@hugeicons/react** should be successfully installed from the npm registry.

Actual Behavior:
The npm registry returns a **404 Not Found error**, indicating that the package cannot be found.

Environment:
Node.js Version: v22.2.0
npm Version: v10.7.0

**Comment by deep93333** [comment]
@cimplify-ai This issue has been fixed in new release today. e have replaced huge icons with open source lucide icons.
